name: Generate API

on:
  push:
    branches:
      - master

jobs:
  generate-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      
      - name: Run API generator
        run: |
          chmod +x ./tools/api-generator.py
          ./tools/api-generator.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git config user.name "api-generator-bot" 
          git config user.email "api-generator-bot@users.noreply.github.com"
          git add -f include/HateEngineAPI.h src/api_sym_lookup_table.h
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "chore: auto-generate HateEngineAPI.h"
          branch: api-generator/update-api
          delete-branch: true
          title: "🤖 Auto-generate HateEngineAPI.h and api_sym_lookup_table.h"
          body: |
            Auto-generated API file from the latest changes.
            
            This PR was automatically created by the API generator workflow.
          labels: |
            automated
            api-generator

      - name: Enable auto-merge
        if: steps.check_changes.outputs.changed == 'true'
        run: gh pr merge --auto --squash api-generator/update-api
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
