name: Generate API

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'include/HateEngineAPI.h'
      - 'src/api_sym_lookup_table.h'

jobs:
  generate-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      
      - name: Run API generator
        run: |
          chmod +x ./tools/api-generator.py
          ./tools/api-generator.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git add -f include/HateEngineAPI.h src/api_sym_lookup_table.h
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "chore: auto-generate HateEngineAPI.h and api_sym_lookup_table.h [ci skip]"
          committer: api-generator-bot <api-generator-bot@users.noreply.github.com>
          author: api-generator-bot <api-generator-bot@users.noreply.github.com>
          branch: api-generator/update-api
          delete-branch: true
          title: "🤖 Auto-generate HateEngineAPI.h and api_sym_lookup_table.h"
          body: |
            Auto-generated API files from the latest changes.
            
            This PR was automatically created by the API generator workflow.
          labels: |
            automated
            api-generator
      
      - name: Enable auto-merge
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          PR_NUMBER=$(gh pr list --head api-generator/update-api --json number --jq '.[0].number')
          gh pr merge --auto --squash "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
